src/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("collections/", include("sw_collections.urls", namespace="sw-collections")),
]

src/sw_collections/urls.py
from django.urls import path
from sw_collections import views

app_name = "sw-collections"

urlpatterns = [
    path("", views.CollectionsView.as_view(), name="list"),
    path("<int:pk>/", views.CollectionsDetailView.as_view(), name="detail"),
    path(
        "<int:pk>/value-counts/",
        views.CollectionsValueCountsView.as_view(),
        name="value-counts",
    ),
    path("fetch/", views.CollectionsFetchView.as_view(), name="fetch"),
]

src/sw_collections/models.py
from typing import Collection

from django.db import models
from django.utils.translation import gettext_lazy as _


class Collection(models.Model):
    csv_file = models.FileField(_("csv file"), upload_to="collections")
    created = models.DateTimeField(_("created"), auto_now_add=True)

    class Meta:
        verbose_name = _("collection")
        verbose_name_plural = _("collections")
        ordering = ("-created",)

src/sw_collections/forms.py
from django import forms

from sw_collections.providers.swapi.entities import Person


class ColumnsForm(forms.Form):
    OPTIONS = (
        (Person.Columns.NAME, Person.Columns.NAME),
        (Person.Columns.HEIGHT, Person.Columns.HEIGHT),
        (Person.Columns.MASS, Person.Columns.MASS),
        (Person.Columns.HAIR_COLOR, Person.Columns.HAIR_COLOR),
        (Person.Columns.SKIN_COLOR, Person.Columns.SKIN_COLOR),
        (Person.Columns.EYE_COLOR, Person.Columns.EYE_COLOR),
        (Person.Columns.BIRTH_YEAR, Person.Columns.BIRTH_YEAR),
        (Person.Columns.GENDER, Person.Columns.GENDER),
        (Person.Columns.HOMEWORLD, Person.Columns.HOMEWORLD),
        (Person.RenamedColumns.DATE, Person.RenamedColumns.DATE),
    )

    columns = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple(attrs={"class": "list-no-bullets"}),
        choices=OPTIONS,
    )

src/sw_collections/views.py
from typing import List

from django.shortcuts import redirect, render
from django.views.generic import DetailView, FormView, ListView, View

from sw_collections.forms import ColumnsForm
from sw_collections.models import Collection
from sw_collections.services import (
    CollectionsDisplayService,
    CollectionsFetchService,
    CollectionsValueCountService,
)


class CollectionsView(ListView):
    model = Collection
    template_name = "sw_collections/list.html"


class CollectionsDetailView(DetailView):
    model = Collection
    template_name = "sw_collections/detail.html"

    default_limit_param = "limit"
    paginate_rows_by = 10

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._display_service = CollectionsDisplayService()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        limit = int(
            self.request.GET.get(self.default_limit_param, self.paginate_rows_by)
        )

        context.update(
            {
                "limit": limit + self.paginate_rows_by,
                "headers": self._display_service.headers,
                "rows": self._display_service.display(self.get_object(), limit),
            }
        )
        return context


class CollectionsValueCountsView(DetailView, FormView):
    model = Collection
    template_name = "sw_collections/value_counts.html"
    form_class = ColumnsForm
    aggr_name = "count"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._value_count_service = CollectionsValueCountService()

    def form_valid(self, form):
        columns: List[str] = form.cleaned_data["columns"]

        context = {
            "form": form,
            "headers": columns + [self.aggr_name],
            "rows": self._value_count_service.count_values(
                self.get_object(), tuple(columns), self.aggr_name
            ),
        }
        return render(self.request, self.template_name, context)


class CollectionsFetchView(View):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._fetch_service = CollectionsFetchService()

    def get(self, *args, **kwargs):
        self._fetch_service.fetch()
        return redirect("sw-collections:list")

src/config/templates/config/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% block style %}
    {% endblock %}
</head>

<body>
    {% include "config/navbar.html" %}
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>

</html>

src/config/templates/config/navbar.html
<header>
    <div class="bg-dark" id="navbarHeader">
        <div class="navbar navbar-dark bg-dark shadow-sm">
            <div class="container d-flex justify-content-between">
                <a href="{% url 'sw-collections:list' %}" class="navbar-brand d-flex align-items-center">
                    <strong>Star Wars Collections</strong>
                </a>
            </div>
        </div>
    </div>
</header>

src/sw_collections/templates/sw_collections/detail.html
{% extends 'config/base.html' %}

{% block title %} {{ object.created }}{% endblock %}

{% block content %}
<p class="h2 pt-4 pb-4">{{ object.csv_file.name }}</p>

{% include "sw_collections/table.html" %}

<a class="btn btn-dark" href="{% url 'sw-collections:detail' object.pk %}?limit={{ limit | urlencode }}">Load more</a>
<a class="btn btn-dark" href="{% url 'sw-collections:value-counts' object.pk %}">Value Counts</a>
{% endblock %}

src/sw_collections/templates/sw_collections/list.html
{% extends 'config/base.html' %}

{% block title %}Star Wars Collections{% endblock %}

{% block content %}
<div class="row pt-3 pb-3">
    <p class="h2 mr-4">Collections</p>
    <a class="btn btn-success h-75" href="{% url 'sw-collections:fetch' %}">Fetch</a>
</div>

<div class="row">
    <ul class="list-group w-100">
        {% for collection in object_list %}
        <li class="list-group-item w-100">
            <a href="{% url 'sw-collections:detail' collection.pk %}">{{ collection.created }}</a>
        </li>
        {% endfor %}
    </ul>
</div>

{% endblock %}

src/sw_collections/templates/sw_collections/table.html
<table class="table table-light">
    <thead class="thead-dark">
        <tr>
            {% for header in headers %}
            <th>{{ header | title }}</th>
            {% endfor %}
        </tr>
    </thead>
    {% for row in rows %}
    <tr>
        {% for column in row %}
        <td>{{ column }}</td>
        {% endfor %}
    </tr>
    {% endfor %}
</table>

src/sw_collections/templates/sw_collections/value_counts.html
{% extends 'config/base.html' %}

{% block title %}Value Counts for {{ obj.created }}{% endblock%}

{% block style %}
<style>
    .list-no-bullets {
        padding-left: 0;
        list-style-type: none;
    }
</style>
{% endblock %}

{% block content %}
<form method="POST" class="mb-5">
    {% csrf_token %}
    {{ form }}
    <input class="btn btn-dark" type="submit" value="Submit">
</form>

{% include "sw_collections/table.html" %}

{% endblock %}